name: alforja
description: Una aplicación móvil para apoyar los controles de viajes al extranjero para comprar artículos.
publish_to: "none"
version: 1.5.18

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  dropdown_search: ^5.0.6
  path: any
  crypto: ^3.0.3
  url_launcher: ^6.3.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: any

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
